@startmindmap
* SP_PBI_Equipment_Event_Empty
** <size:20><b><color:LightPink>Initialize</color></b></size>
*** Variables
*** Drop existing `Z_PBI_Equipment_Event_EM_temp`
*** Create `Z_PBI_Equipment_Event_EM_temp`
** <size:20><b><color:LightPink>Insert Data</color></b></size>
*** Source: `PBI_Equipment_Cycle_Sub`
*** Filter: Event types [MST, MRY, MSH, MCY]
*** Insert into temp table
** <size:20><b><color:LightPink>Update Data</color></b></size>
*** Update `Rail_Truck` and `Rail_Truck_ID`
*** Source: `PBI_CODECO_Cache`
** <size:20><b><color:LightPink>Finalize</color></b></size>
*** Drop old `Z_PBI_Equipment_Event_EM`
*** Rename temp table to `Z_PBI_Equipment_Event_EM`
*** Update timestamp in `DB_Param`
@endmindmap
