@startmindmap
* <size:40><b>Equipment Data Flow</b></size>
** <size:20><b><color:YellowGreen>MAIN Data Sources</color></b></size>
*** PBI_Equipment_Cycle_Sub
**** <i>Contains all equipment cycles</i>
**** Fields:
***** <b>Event Time</b>
***** <b>Voyage Port Call ID</b>
***** Depot
***** Port of Load
***** Port of Discharge
***** Booking Number
***** Bill of Lading Number
*** PBI_Agency_CSC
**** <i>Contains all documents</i>
**** Fields:
***** <b>Equipment_id</b>
***** <b>Voyage_Port_Call_id</b>
***** Booking Number
***** Bill of Lading Number
***** I/E
*** PBI_CODECO_Cache
**** <u>Received from EDI CODECO files</u>
**** Updates Rail_Truck & Rail_Truck_ID

** <size:20><b><color:LightPink>Event Categories</color></b></size>
*** <&check> Import Full
*** <&check> Export Full
*** <&check> Empty

** <size:20><b><color:LightBlue>Key Tables</color></b></size>
*** PBI_Equipment_Cycle_Sub
**** <b>Central table for all cycles</b>
*** Z_PBI_Equipment_Event_E
**** Export Full
*** Z_PBI_Equipment_Event_I
**** Import Full
*** Z_PBI_Equipment_Event_EM
**** Empty Equipment

** <size:20><b><color:LightGray>TABLE Relationships</color></b></size>
*** PBI_Equipment_Cycle_Sub joins with temporary table
**** Filters based on I/E or EventType
*** PBI_CODECO_Cache updates event tables
**** Based on Equipment_Number and EDI_Filename
@endmindmap
