name: Render PlantUML Diagrams

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permette di eseguire il workflow manualmente

jobs:
  render-puml:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Java environment using AdoptOpenJDK
      - name: Setup Java (AdoptOpenJDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'  # Usa AdoptOpenJDK
          java-version: '21'     # Specifica la versione 21 (come installato localmente)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      # Step 4: Download PlantUML
      - name: Download PlantUML
        run: |
          mkdir -p tools
          curl -L https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar -o tools/plantuml.jar

      # Step 5: Debug - Visualizza il contenuto del file .puml
      - name: Debug - Visualizza contenuto file .puml
        run: |
          echo "Checking content of PlantUML file:"
          cat DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.puml

      # Step 6: Render PlantUML diagram
      - name: Render PlantUML diagram
        run: |
          TIMESTAMP=$(date +'%Y%m%d_%H%M%S')
          mkdir -p DCC_Trasporti_H/ # Assicura che la directory esista
          java -jar tools/plantuml.jar -tpng DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.puml -o DCC_Trasporti_H/ || {
            echo "PlantUML rendering failed. Checking tools directory and file permissions.";
            ls -l tools;
            ls -l DCC_Trasporti_H/;
            exit 1;
          }
          if [ -f "DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.png" ]; then
            echo "PNG generated successfully:"
            ls -l DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.png
            mv DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.png DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub_${TIMESTAMP}.png
          else
            echo "PNG generation failed. Checking tools directory and output:"
            ls -l tools
            ls -l DCC_Trasporti_H/
            exit 1
          fi

      # Step 7: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-diagram
          path: DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub_*.png