jobs:
  render-puml:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Java environment
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      # Step 4: Download PlantUML jar
      - name: Download PlantUML
        run: |
          mkdir -p tools
          curl -L https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar -o tools/plantuml.jar

      # Step 5: Generate PNG with timestamp in filename
      - name: Generate diagram
        run: |
          TIMESTAMP=$(date +'%Y%m%d_%H%M%S') # Calculate timestamp
          java -jar tools/plantuml.jar -tpng DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.puml -o DCC_Trasporti_H/
          mv DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.png DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub_${TIMESTAMP}.png

      # Step 6: Commit and push the PNG to the repository
      - name: Commit and push PNG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub_*.png
          git commit -m "Add generated diagram: FNTB_Equipment_Cycle_Sub_${TIMESTAMP}.png"
          git push

      # Step 7: Upload artifact (optional, to keep the current behavior)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-diagram
          path: DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub_*.png
