name: Render PlantUML Diagram

on:
  push:
    paths:
      - 'DCC_Trasporti_H/*.puml' # Trigger solo per modifiche ai file .puml in questa directory
  workflow_dispatch: # Permette l'esecuzione manuale del workflow

jobs:
  render-puml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Download PlantUML JAR
        run: |
          mkdir -p tools
          curl -L https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar -o tools/plantuml.jar

      - name: Render diagram
        run: |
          java -jar tools/plantuml.jar -tpng DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.puml -o DCC_Trasporti_H/
