name: Render PlantUML Diagrams

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permette di eseguire il workflow manualmente

jobs:
  render-puml:
    runs-on: ubuntu-22.04 # Specifica esplicitamente la versione di Ubuntu
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Java environment
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Specifica la distribuzione Java (ad esempio 'temurin', 'zulu', ecc.)
          java-version: '11'      # Specifica la versione di Java

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      # Step 4: Download PlantUML jar
      - name: Download PlantUML
        run: |
          mkdir -p tools
          curl -L https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar -o tools/plantuml.jar

      # Step 5: Debug - Visualizza il contenuto del file .puml
      - name: Debug - Visualizza contenuto file .puml
        run: |
          echo "Checking content of PlantUML file:"
          cat DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.puml

      # Step 6: Debugging PlantUML Rendering (aggiunta causa 2 e controllo dettagliato)
      - name: Debug PlantUML Rendering
        run: |
          TIMESTAMP=$(date +'%Y%m%d_%H%M%S')
          mkdir -p DCC_Trasporti_H/ # Assicura che la directory esista
          echo "Rendering the following PlantUML content:"
          cat DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.puml
          java -jar tools/plantuml.jar -tpng DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.puml -o DCC_Trasporti_H/ || {
            echo "PlantUML rendering failed. Checking tools directory and file permissions.";
            ls -l tools;
            ls -l DCC_Trasporti_H/;
            exit 1;
          }
          if [ -f "DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.png" ]; then
            echo "PNG generated successfully:"
            ls -l DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.png
            mv DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.png DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub_${TIMESTAMP}.png
          else
            echo "PNG generation failed. Checking tools directory and output:"
            ls -l tools
            ls -l DCC_Trasporti_H/
            exit 1
          fi

      # Step 7: Generate PNG with timestamp in filename (aggiunta causa 1 e 3)
      - name: Generate diagram
        run: |
          TIMESTAMP=$(date +'%Y%m%d_%H%M%S') # Calcola timestamp
          mkdir -p DCC_Trasporti_H/ # Assicura che la directory esista
          java -jar tools/plantuml.jar -tpng DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.puml -o DCC_Trasporti_H/ || {
            echo "PlantUML rendering failed during second attempt. Checking tools and output:";
            ls -l tools;
            ls -l DCC_Trasporti_H/;
            exit 1;
          }
          if [ -f "DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.png" ]; then
            mv DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.png DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub_${TIMESTAMP}.png
            echo "PNG successfully renamed with timestamp: DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub_${TIMESTAMP}.png"
          else
            echo "PNG generation failed during diagram step."
            exit 1
          fi

      # Step 8: Commit and push the PNG to the repository
      - name: Commit and push PNG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub_*.png
          git commit -m "Add generated diagram: FNTB_Equipment_Cycle_Sub_${TIMESTAMP}.png"
          git push

      # Step 9: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-diagram
          path: DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub_*.png
